# This is a basic workflow to help you get started with Actions

name: Syntax.Rocks actions
on:
  push:
    branches: [ master ]
jobs:
  update-readme-upon-post-addition:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: add-gatsby-blog-meta-info-to-readme
      uses: ananta/add-contributors-action@master
      with:
        title: "Blog Posts"
